runtime: custom
env: flex
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# entrypoint: gunicorn -w 2 --threads 8 -b :$PORT main:app

# runtime_config:
#   python_version: 3

# manual_scaling:
#   instances: 1

# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10
